name: nf_clone
description: A clone version of Netflix Original application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  tmdb_api: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/net.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Mont
      fonts:
        - asset: assets/fonts/Mont-Black.otf
        - asset: assets/fonts/Mont-Regular.otf